# Generated by Django 4.1 on 2022-08-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Post',
        ),
    ]
