# Generated by Django 4.1 on 2022-08-14 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseApi', '0002_rename_question_category_rename_choice_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='question',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='choice_text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
