# Generated by Django 4.1 on 2022-08-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApi', '0005_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='details',
            new_name='detail',
        ),
    ]
